services:
  
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
      - serverIP=192.168.1.46
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /config/tdarr/server:/app/server
      - /config/tdarr/configs:/app/configs
      - /config/tdarr/logs:/app/logs
      - ${LOAS}/media:/media
      - /transcode_cache:/temp
    ports:
      - 8265:8265
      - 8266:8266
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
      - nodeName=MyExternalNode
      - serverIP=192.168.1.46
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=6
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /config/tdarr/configs:/app/configs
      - /config/tdarr/logs:/app/logs
      - ${LOAS}/media:/media
      - /transcode_cache:/temp
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    network_mode: service:tdarr
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/radarr:/config
      - ${LOAS}/media/movies:/movies
      - ${LOAS}/usenet:/usenet
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/sonarr:/config
      - ${LOAS}/media/tv:/tv
      - ${LOAS}/usenet:/usenet
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/bazarr:/config
      - ${LOAS}/media/movies:/movies
      - ${LOAS}/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/prowlarr:/config
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/sabnzbd:/config
      - ${LOAS}/usenet:/usenet
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    container_name: plexautolanguages
    environment:
      - PLEX_URL=http://192.168.1.47:32400
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TZ=${TZ}    
    volumes:
      - /config/plexautolanguages:/config
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
