services:

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${ROOT}/config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${ROOT}/config/radarr:/config
      - ${LOAS}/media/movies:/movies
      - ${LOAS}/usenet:/usenet
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${ROOT}/config/sonarr:/config
      - ${LOAS}/media/tv:/tv
      - ${LOAS}/usenet:/usenet
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${LOAS}/media/movies:/movies
      - ${LOAS}/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${ROOT}/config/whisparr:/config
      - ${LOAS}/media/xxx:/xxx
      - ${LOAS}/usenet:/usenet
    ports:
      - 6969:6969
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${ROOT}/config/prowlarr:/config
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${ROOT}/config/sabnzbd:/config
      - ${LOAS}/usenet:/usenet
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  plex:
    runtime: nvidia
    privileged: true
    container_name: plex
    hostname: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - VERSION=docker
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    network_mode: host
    volumes:
      - ${ROOT}/config/plexdb:/config
      - ${TRANSCODE}:/transcode
      - ${LOAS}/media/movies:/movies
      - ${LOAS}/media/tv:/tv
      - ${LOAS}/media/xxx:/xxx
    labels:
      - com.centurylinklabs.watchtower.enable=true

  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    container_name: plexautolanguages
    environment:
      - PLEX_URL=http://192.168.1.45:32400
      - PLEX_TOKEN=fmdSEyKQuRrNnQiWLys8
      - TZ=${TZ}    
    volumes:
     - ${ROOT}/config/plexautolanguages:/config
    network_mode: host
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    network_mode: host
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${LOAS}/media/xxx:/xxx
      - ${ROOT}/config/stash/config:/root/.stash
      - ${ROOT}/config/stash/metadata:/metadata
      - ${ROOT}/config/stash/cache:/cache
      - ${ROOT}/config/stash/blobs:/blobs
      - ${ROOT}/config/stash/generated:/generated

networks:
  multimediaservices_network:
    external: true