version: "3.8"
services:

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/radarr:/config
      - ${MEDIA}/movies:/movies
      - ${CHARON}/sabnzbd/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/sonarr:/config
      - ${MEDIA}/tv:/tv
      - ${CHARON}/sabnzbd/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${MEDIA}/movies:/movies
      - ${MEDIA}/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/whisparr:/config
      - ${MEDIA}/xxx:/xxx
      - ${CHARON}/sabnzbd/downloads:/downloads
    ports:
      - 6969:6969
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/prowlarr:/config
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/sabnzbd:/config
      - ${CHARON}/sabnzbd/downloads:/downloads
      - ${CHARON}/sabnzbd/downloads/intermediate:/intermediate
      - ${CHARON}/sabnzbd/downloads/completed:/completed
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - multimediaservices_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  plex:
    runtime: nvidia
    privileged: true
    container_name: plex
    hostname: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - VERSION=docker
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    network_mode: host
    volumes:
      - ${ROOT}/config/plexdb:/config
      - ${ROOT}/transcode:/transcode
      - ${MEDIA}/movies:/movies
      - ${MEDIA}/tv:/tv
      - ${MEDIA}/xxx:/xxx
    labels:
      - com.centurylinklabs.watchtower.enable=true

  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    container_name: plexautolanguages
    environment:
      - PLEX_URL=http://192.168.1.45:32400
      - PLEX_TOKEN=reKFC-C828Gqv6aJ2ehG
      - TZ=${TZ}    
    volumes:
     - ${ROOT}/config/plexautolanguages:/config
    network_mode: host
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  multimediaservices_network:
    external: true