services:
  
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/overseerr:/config
    ports:
      - ${OVERSEERR_PORT}:5055
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOADS_DIR}:/usenet
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/sonarr:/config
      - ${TV_DIR}:/tv
      - ${DOWNLOADS_DIR}:/usenet
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/bazarr:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
    ports:
      - ${BAZARR_PORT}:6767
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - ${PROWLARR_PORT}:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/prowlarr:/config
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/sabnzbd:/config
      - ${DOWNLOADS_DIR}:/usenet
    ports:
      - ${SABNZBD_PORT}:8080
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    container_name: plexautolanguages
    environment:
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TZ=${TZ}    
    volumes:
      - /config/plexautolanguages:/config
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      