---
# Media services configuration
name: helios-media

# Common configuration
x-common: &common-settings
  restart: unless-stopped
  environment: &common-env
    PUID: ${PUID}
    PGID: ${PGID}
    TZ: ${TZ}
    UMASK: ${UMASK}
  labels: &common-labels
    - com.centurylinklabs.watchtower.enable=true

services:
  
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_DIR}/overseerr:/config
    ports:
      - ${OVERSEERR_PORT}:5055
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOADS_DIR}:/usenet
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${TV_DIR}:/tv
      - ${DOWNLOADS_DIR}:/usenet
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
    ports:
      - ${BAZARR_PORT}:6767
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - ${PROWLARR_PORT}:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_DIR}/sabnzbd:/config
      - ${DOWNLOADS_DIR}:/usenet
    ports:
      - ${SABNZBD_PORT}:8080
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  plexautolanguages:
    image: remirigal/plex-auto-languages:latest
    container_name: plexautolanguages
    environment:
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TZ=${TZ}    
    volumes:
      - ${CONFIG_DIR}/plexautolanguages:/config
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    runtime: nvidia
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=HeliosNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${CONFIG_DIR}/tdarr:/config
      - ${CONFIG_DIR}/tdarr/temp:/temp
      - ${MOVIES_DIR}:/movies:ro
      - ${TV_DIR}:/tv:ro
      - ${DOWNLOADS_DIR}/movies:/downloads/movies:ro
      - ${DOWNLOADS_DIR}/tv:/downloads/tv:ro
      - ${DOWNLOADS_DIR}/default:/downloads/default:ro
      - ${DOWNLOADS_DIR}/those:/downloads/those:ro
    ports:
      - 8265:8265  # WebUI port
      - 8266:8266  # Server port
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      