services:

  agent:
    image: portainer/agent:latest
    container_name: portaineragent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - agent_network
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    runtime: nvidia
    privileged: true
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - portainer_data:/data
      - /usr/share/hwdata/pci.ids:/usr/share/hwdata/pci.ids
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      - agent_network
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 3600 --label-enable --cleanup --remove-volumes

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    environment:
        - TZ=${TZ}
    volumes:
        - adguardhome_data:/opt/adguardhome/work
        - adguardhome_data:/opt/adguardhome/conf
    network_mode: host
    ports:
        - 53:53/tcp
        - 53:53/udp
        - 67:67/udp
        - 68:68/udp
        - 80:80/tcp
        - 443:443/tcp
        - 443:443/udp
        - 3000:3000/tcp
        - 853:853/tcp
        - 853:853/udp
        - 5443:5443/tcp
        - 5443:5443/udp
        - 6060:6060/tcp
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - ${PORT:-8191}:8191
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
      - PASSWORD=Arrowleaf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT}/config/homarr/config:/app/data/configs
      - ${ROOT}/config/homarr/icons:/app/public/icons
      - ${ROOT}/config/homarr/icons:/app/public/imgs/backgrounds
      - ${ROOT}/config/homarr/icons:/app/public/imgs/logo
      - homarr_data:/data
    ports:
      - 7575:7575
    labels:
      - com.centurylinklabs.watchtower.enable=true

  dash:
    image: mauricenino/dashdot:nvidia
    container_name: dash
    runtime: nvidia
    privileged: true
    environment:
      - DASHDOT_WIDGET_LIST=os,cpu,storage,ram,network,gpu
      - DASHDOT_USE_NETWORK_INTERFACE=eno1
    ports:
      - 81:3001
    volumes:
      - /:/mnt/host:ro
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  scrutiny:
    container_name: scrutiny
    privileged: true
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - 8081:8080
      - 8086:8086
    volumes:
      - /run/udev:/run/udev:ro
      - ${ROOT}/config/scrutiny/config:/opt/scrutiny/config
      - ${ROOT}/config/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
      - /dev/nvme0n1
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  agent_network:
  multimediaservices_network:

volumes:
  portainer_data:
  homarr_data:
  dockovpn_data:
  adguardhome_data: