services:

  agent:
    image: portainer/agent:latest
    container_name: portaineragent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - agent_network
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    privileged: true
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 3600 --label-enable --cleanup --remove-volumes

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - ${PORT:-8191}:8191
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
      - PASSWORD=Arrowleaf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /config/homarr/config:/app/data/configs
      - /config/homarr/icons:/app/public/icons
      - /config/homarr/imgs:/app/public/imgs
      - homarr_data:/data
    ports:
      - 7575:7575
    labels:
      - com.centurylinklabs.watchtower.enable=true

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=984
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /config/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  agent_network:

volumes:
  portainer_data:
  homarr_data:
  beszel_data:
