services:
  agent:
    image: portainer/agent:latest
    container_name: portaineragent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - agent_network
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    privileged: true
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - ${PORTAINER_SSL_PORT}:9443
      - ${PORTAINER_PORT}:8000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 3600 --label-enable --cleanup --remove-volumes

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - ${FLARESOLVERR_PORT}:8191
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - PASSWORD=${HOMARR_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/homarr/config:/app/data/configs
      - ${CONFIG_DIR}/homarr/icons:/app/public/icons
      - ${CONFIG_DIR}/homarr/imgs:/app/public/imgs
      - homarr_data:/data
    ports:
      - ${HOMARR_PORT}:7575
    labels:
      - com.centurylinklabs.watchtower.enable=true

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
    ports:
      - ${TAUTULLI_PORT}:8181
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - ${N8N_PORT}:5678
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_TUNNEL_URL=${N8N_WEBHOOK_TUNNEL_URL}
    volumes:
      - n8n_data:/home/node/.n8n
      - ${CONFIG_DIR}/n8n:/config
      - /etc/HELIOS/secrets.sh:/secrets.sh:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  agent_network:

volumes:
  portainer_data:
  homarr_data:
  n8n_data: