version: "3.8"
services:

  dockovpn:
    container_name: dockovpn
    image: alekslitvinenk/openvpn:latest
    cap_add:
        - NET_ADMIN
    ports:
        - 1194:1194/udp
    environment:
        HOST_ADDR: ${HOST_ADDR}
    volumes:
        - dockovpn_data:/opt/Dockovpn_data
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  agent:
    image: portainer/agent:latest
    container_name: portaineragent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - agent_network
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    runtime: nvidia
    privileged: true
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - 9443:9443
      - 8001:9000
    volumes:
      - portainer_data:/data
      - /usr/share/hwdata/pci.ids:/usr/share/hwdata/pci.ids
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      - agent_network
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 3600 --label-enable --cleanup --remove-volumes

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8081:80/tcp
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=Arrowleaf
    volumes:
      - ${ROOT}/config/pihole/etc-pihole:/etc/pihole/
      - ${ROOT}/config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
      - PASSWORD=Arrowleaf
    volumes:
      - ${ROOT}/config/homarr/config:/app/data/configs
      - ${ROOT}/config/homarr/icons:/app/public/icons
      - ${ROOT}/config/homarr/icons:/app/public/img
      - homarr_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7575:7575
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  agent_network:
  multimediaservices_network:

volumes:
  portainer_data:
  homarr_data:
  dockovpn_data: